### ISSUE TITLE
Untested return value undefined

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#519]
```
undefined local variable or method `s' for #<SolrDocument:0x007fa7f30ebe68>
```

https://github.com/geoblacklight/geoblacklight/blob/master/app/models/concerns/geoblacklight/solr_document.rb#L71

Introduced in https://github.com/geoblacklight/geoblacklight/commit/b6a042649c452dd0fa5a42e62ff499223031d6c0#diff-85accdb69279a3f1bbc2b3c5109e552eL55
