### ISSUE TITLE
Template Install Issues Part 2

### ISSUE THREAD

**Issue by dl-maura** [geoblacklight/geoblacklight#1266]
### Descriptive summary

We had worked on the template before in a ticket (https://github.com/orgs/geoblacklight/projects/2/views/12?filterQuery=template&pane=issue&itemId=7443019) but a number of us are still seeing issues using the quick start (DISABLE_SPRING=1 rails new app-name -m https://raw.githubusercontent.com/geoblacklight/geoblacklight/main/template.rb) not working if you are on Rails 7 (can confirm it works on Rails 6 with ruby 2.7, have not tried with Ruby 3 and rails 6).

### Expected behavior

Someone should be able to run this with rails 6 OR 7, and ruby 2 OR 3 and have this complete successfully.

### Actual behavior

If you're on Rails 7 and Ruby 2, the blacklight devise step just hangs (no errors but it will never complete). 

Others have reported the following error on Ruby 3 + Rails 7:
/var/www/rubyapps/uwm-geoblacklight/app/controllers/catalog_controller.rb:32:in `block in <class:CatalogController>': undefined method `title_field=' for {:rows=>10}:Hash (NoMethodError)

### Steps to reproduce the behavior

Be in an environment with rails 7 installed and try the template, it will fail on devise step.

OR

Be in an environment that is Ruby 3 + Rails 7 -- may not get to the devise step.

### Related work
https://github.com/orgs/geoblacklight/projects/2/views/12?filterQuery=template&pane=issue&itemId=7443019

**Comment by ewlarson** [comment]
The template install worked for me with Rails 7 and Ruby 3.1 last week.

**Comment by dl-maura** [comment]
Ok so!

Rails 6 + ruby 2 -> works
Rails 7 + ruby 3 -> works
Rails 7 + ruby 2 -> works

But it is worth noting that the ruby 2 installs throw up a ton of warning, so it may be we want to recommend ruby 3 and rails 7?

**Comment by ewlarson** [comment]
Ruby 2.7 is EOL at the end of this month:
https://endoflife.date/ruby

We should recommend Ruby 3.2 and Rails 7.0 for anyone just getting started.
